version: '4'
networks:
  tasknet:
    driver: bridge
#  host.docker.internal:
services:
  nginx:
    platform: linux/x86_64
    image: nginx:stable-alpine
    container_name: nginx_task
    ports:
      - "8088:80"
    depends_on:
      - php
    volumes:
      - ./web:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    #    env_file:
    #      - ./config/local.env
    restart: always
    networks:
      - tasknet
  php:
    platform: linux/x86_64
    build:
      context: .
      dockerfile: Dockerfile_php
    container_name: php_task
    ports:
      - '9000:9000'
    expose:
      - '9000'
    volumes:
      - ./web:/var/www/html
    #    env_file:
    #      - ./config/local.env
    restart: always
    networks:
      - tasknet

  api_task:
    platform: linux/x86_64
    build:
      context: ./
      dockerfile: Dockerfile_apitask
    container_name: api_task
    ports:
      - '3001:3001'
      - '3002:3002'
    expose:
      - '3001'
      - '3002'
    volumes:
      - './api_task/:/app'
    restart: always
    networks:
      - tasknet

volumes:
  nginx:
  web:
  api_task:
  db:


