version: '3.8'
networks:
    tasknet:
        driver: bridge
#  host.docker.internal:
services:
    nginx:
        platform: linux/x86_64
        image: nginx:stable-alpine
        container_name: nginx_task
        restart: always
        ports:
          - "8088:80"
        depends_on:
          - php
        volumes:
          - ./web:/var/www/html
          - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        env_file:
            - ./config/local.env
        networks:
          - tasknet
    php:
        platform: linux/x86_64
        build: 
          context: .
          dockerfile: Dockerfile_php
        container_name: php_task
        restart: always
        ports:
            - '3000:3000'
        expose:
            - '3000'
        environment:
          XDEBUG_TRIGGER: 1
          PHP_IDE_CONFIG: serverName=host.docker.internal
        volumes:
            - ./web:/var/www/html
        env_file:
            - ./config/local.env
        networks:
          - tasknet

    api_task:
        platform: linux/x86_64
        build:
          context: ./
          dockerfile: Dockerfile_apitask
        container_name: api_task
        restart: always
        ports :
          - '3001:3001'
        expose:
          - '3001'
        volumes:
          - './api_task/:/src'   
        networks:
          - tasknet       
                      
volumes:
  nginx:
  web:
  api_task:
  db:  

